stages:
  - qa
  - docs
  - test

manifest:
  stage: qa
  script:
    - pip install tox tox-uv
    - tox -e manifest

lint:
  stage: qa
  script:
    - pip install tox tox-uv
    - tox -e lint

pyroma:
  stage: qa
  script:
    - pip install tox tox-uv
    - tox -e pyroma

mypy:
  stage: qa
  script:
    - pip install tox tox-uv
    - tox -e mypy

doc8:
  stage: docs
  script:
    - pip install tox tox-uv
    - tox -e doc8

docstrs:
  stage: docs
  script:
    - pip install tox tox-uv
    - tox -e docstr-coverage

docs:
  stage: docs
  script:
    - pip install tox tox-uv
    - tox -e docs

tests:
  stage: test
  script:
    - pip install tox tox-uv
    - tox -e py

doctests:
  stage: test
  script:
    - pip install tox tox-uv
    - tox -e doctests

treon:
  stage: test
  script:
    - pip install tox tox-uv
    - tox -e treon
