# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  apt_packages:
    - graphviz
  tools:
    python: "3.12"

python:
  install:
    # partial override of build commands was added in https://github.com/readthedocs/readthedocs.org/pull/11710
    # you can include extras with .[] notation
    - pip install --dependency-groups=docs .
