[doc("run unit and integration tests")]
test:
    # See the [dependency-groups] entry in pyproject.toml for "tests"
    just coverage erase
    uv run --group tests --all-extras -m coverage run -p -m pytest
    just coverage combine
    just coverage report
    just coverage html

[doc("remove testing coverage artifacts")]
coverage-clean:
    just coverage erase

[doc("run `coverage` with a given subcommand")]
@coverage command:
    uvx --from coverage[toml] coverage {% raw %}{{command}}{% endraw %}

[doc("test that documentation examples run properly")]
doctests:
    #  note that the package name is required for discovery
    uv run --group doctests --all-extras xdoctest -m src/{{ cookiecutter.package_name }}

[doc("test that notebooks can be run to completion")]
treon:
    uv run treon

[doc("format code")]
format:
    #  Note that ruff check should come before ruff format when using --fix (ref: https://github.com/astral-sh/ruff-pre-commit/blob/main/README.md)
    uvx ruff check --fix
    uvx ruff format

[doc("format documentation")]
format-docs:
    # note that this doesn't work with sphinx-click
    # or any other extension that adds extra directives
    # See the [dependency-groups] entry in pyproject.toml for "rstfmt"
    uv run --group format-docs docstrfmt src/ tests/ docs/ --no-docstring-trailing-line

[doc("format documentation")]
format-markdown:
    npx --yes prettier --write --prose-wrap always "**/*.md"

[doc("check code quality")]
lint:
    uvx ruff check
    uvx ruff format --check

[doc("check markdown is properly formatted")]
lint-markdown:
    # inspired by https://github.com/astral-sh/uv/blob/98523e2014e9a5c69706623344026d76296e178f/.github/workflows/ci.yml#L67C1-L70C61
    npx --yes prettier --check --prose-wrap always "**/*.md"

[doc("run the pyroma tool to check the package friendliness of the project")]
pyroma:
    uv run --group pyroma pyroma --min=10 .

[doc("run the mypy tool to check static typing on the project")]
mypy:
    uv run --group typing mypy --ignore-missing-imports --strict src/ tests/
